### ISSUE TITLE
Bullet Rendering

### ISSUE THREAD

**Issue by robodreamer** [bminortx/Buckshot#1]
Considering more computations that will be involved later for different projects, it would be great if SimLab can provide another option for rendering using OpenGL or SceneGraph, and etc. Right now the rendering seems the big bottleneck for the simulation. Thanks for opening the source of this great tool. I really appreciate it and would like to help making it better and more flexible for various projects.

**Comment by bminortx** [comment]
Thanks for your praise! I worked hard on the system, so it's nice to know it's utilized. 

Good point. This was one of the main issues that I ran into when I first started building this tool; MATLAB's graphics are just not up for the rendering we need. I've been experimenting with a third-party graphics engine through SceneGraph (https://github.com/arpg/SceneGraph). It works well, but I haven't had time to upload it, since I unfortunately don't have a working computer right now.

It's a sad day.

However, give me a week, and I'll post my personal solution. If you have any potential solution yourself, fork the repo and I can check it out. That goes for any part of the project, really. Think you have an improvement? Submit a PR request and we can put it into the system.

**Comment by robodreamer** [comment]
Hi Brandon, hope everything is going well with you! It would be great if you could share your personal solution using SceneGraph with me! Hope you got your computer working now. Thanks so much!

**Comment by bminortx** [comment]
I'm back! It's been a while. Look forward to that SceneGraph implementation.

**Comment by bminortx** [comment]
Getting back to this. Should have a good solution by the beginning of December, I think.

**Comment by bminortx** [comment]
Ok, @robodreamer, take a look now, if you're still interested. I would love to get some help with the graphics, or just more issue logs about what could be improved (the list is long)
